---
version: "3"
services:
  #Nginx Service
  api:
    # It will look for a dockerfile in the project root and build it
    image: bayesimpact/react-base
    # Exposes the port 5000 from a container and binds it to a random port
    ports:
      - "8080"
    # If the container goes down, it will restart
    restart: "always"
    # Connects the API to a common api.network bridge
    networks:
      - "mynetwork"
    # Starts up 5 replicas of the same image
    deploy:
      replicas: 2
    # nginx container
  nginx:
    # specifies the latest nginx image
    image: nginx:latest
    # Connects the conf file of the container to the conf file in our folder
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # It will start up the nginx only when all api containers have started
    depends_on:
      - api
    # Connects the port 80 of the nginx container to localhost:80 or localhost
    ports:
      - "80:8080"
    networks:
      - "mynetwork"

  # mysql service
  mysql:
    image: "percona:8"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    networks:
      - mynetwork
  #Docker Networks
networks:
  mynetwork:
